name: build

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 2.7
      - name: Install dependencies
        run: |
          conda install --yes pandas nose
      - name: Run tests
        run: |
          nosetests -a UNIT test/unit
